# Generated by Django 4.2 on 2023-04-14 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debtsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='debtsApp.user'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debtsApp.debtor'),
        ),
    ]
