# Generated by Django 4.2 on 2023-04-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtsApp', '0003_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtor',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
