# Generated by Django 4.2 on 2023-04-15 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debtsApp', '0005_rename_debt_debt_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='debtsApp.debtor'),
        ),
    ]
